version: '3.5'
volumes:
  orcid_data:
services:
  db:
    image: postgres:10.4
    hostname: dev-db.orcid.org
    volumes:
      - ./tomcat/initdb:/docker-entrypoint-initdb.d
      - orcid_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD:${PG_PASSWORD:-orcid}"
    ports:
      - "5432:5432"
  web:
    build: tomcat
    image: orcid/tomcat
    hostname: dev.orcid.org
    volumes:
      - ${ORCID_SOURCE}:/orcid_source
      - ./tomcat:/orcid
    links:
      - db:dev-db.orcid.org
    depends_on:
      - db
      - src
    ports:
      - "8443:${ORCID_WEB_PORT_SSL:-8443}"
      - "8080:${ORCID_WEB_PORT:-8080}"
